# Gruvbox Dark Theme
# Tema cálido y oscuro con tonos terrosos

# Colores básicos
foreground #ebdbb2
background #1d2021
background_opacity 0.5

# Cursor
cursor #fbf1c7

# Colores negros
color0 #282828
color8 #928374

# Colores rojos
color1 #cc241d
color9 #fb4934

# Colores verdes
color2  #98971a
color10 #b8bb26

# Colores amarillos
color3  #d79921
color11 #fabd2f

# Colores azules
color4  #458588
color12 #83a598

# Colores magentas
color5  #b16286
color13 #d3869b

# Colores cyans
color6  #689d6a
color14 #8ec07c

# Colores blancos
color7  #a89984
color15 #ebdbb2

# Selección
selection_foreground #282828
selection_background #fabd2f

# Pestañas
active_tab_foreground   #282828
active_tab_background   #fabd2f
active_tab_font_style   bold
inactive_tab_foreground #a89984
inactive_tab_background #3c3836
inactive_tab_font_style normal
tab_bar_background #1d2021
