#!/bin/sh
#THIS IS A GRUB PROXY SCRIPT
'/etc/grub.d/proxifiedScripts/custom' | /etc/grub.d/bin/grubcfg_proxy "-*
-#text
-'BlackArch'~529032706c381e4ad8b96adbd12b90f5~
-'CarchyOS'~5324137a6a7e664cfd92b2fa4356924e~
-'CarchyOS-hardened'~2c3e0a120e86a669e887ef30b1cdd3f6~
+'BlackArch-hardened'~5ec3f02d186b6ab6a46cf3d8ee8dfcff~
"