-- Generated by nwg-displays on 2026-07-24 at 08:46:16. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x9125",
    mode = "1920x1200@60.0",
    position = "0x1080",
    scale = 1.2
})
hl.monitor({
    output = "desc:Microstep MSI MP223 PB9H164200053",
    mode = "1920x1080@100.0",
    position = "0x0",
    scale = 1.0
})
