# ### Hyprland ###
# Apps
$terminal = kitty
$browser = brave
$editor = code --password-store="gnome-libsecret"
$fileExplorer = dolphin
$gitEditor = gitkraken

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.3
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = false
$blurPopups = true
$blurInputMethods = true
$blurSize = 8
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 5
$windowGapsIn = 5
$windowGapsOut = 5
$singleWindowGapsOut = 5

# Window styling
$windowOpacity = 0.90
$windowRounding = 10

$windowBorderSize = 3
$activeWindowBorderColour = rgba(82b176ff)
$groupedWindowBorderColour = rgba(ffcc99ee)
$groupedLockedWindowBorderColour = rgba(e77778ff)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 10  # In percent
$cursorTheme = sweet-cursors
$cursorSize = 24


# ### Keybinds ###
# Workspaces
$kbMoveWinToWs = Super+Alt
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Super, S

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbReorderWindow = Super, N
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super+Shift, F
$kbCloseWindow = Super, Q

# Special workspace toggles
$kbSystemMonitor = Ctrl+Shift, Escape
$kbMusic = Super, M
$kbCommunication = Super, W
$kbTodo = Super, R

# Apps
$kbTerminal = Super, T
$kbBrowser = Super, B
$kbEditor = Super, C
$kbFileExplorer = Super, E
$kbGitEditor = Super, G

# Misc
$kbSession = Ctrl+Alt, Delete
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, I
$kbLock = Super, O
$kbRestoreLock = Super+Alt, O
