[General]
# Path to the wallpaper. If it's in the assets folder, use "assets/background.jpg"
background=assets/background.jpg

# Material You-like colors (we can refine these)
primaryColor=#9099A8
accentColor=#5A6575
backgroundColor=#13171A
textColor=#C5CCDB

# Font settings
fontFamily=Google Sans Flex Freeze
fontSize=12
